# Author @mvxt
version: 2.1

#####################
# Common Definitions
#####################
# Simple YAML anchors
aliases:
  - &project_dir "~/project"

# Executors
executors:
  dart-exec:
    docker:
      - image: google/dart:2.9.1

######################
# Workflow Definition
######################
workflows:
  version: 2.1
  test-and-build:
    jobs:
      - test

##################
# Job Definitions
##################
jobs:
  test:
    executor: dart-exec
    steps:
      - checkout
      - run:
          name: Download deps
          command: pub get
      - run:
          name: Get junitreporter
          command: pub global activate junitreport
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      - run:
          name: Run tests
          command: pub run test --reporter json | tojunit --output test-results/dart-tests/circleci_dart_demo_test-report.xml
      - store_test_results:
          path: test-results

